
export const ADD_INGREDIENTS = "ADD_INGREDIENTS";
export const REMOVE_INGREDIENTS = "REMOVE_INGREDIENTS"
export const    SET_INGREDIENTS = "SET_INGREDIENTS" 
export const  SET_ERROR = "SET_ERROR"
export const PURCHASE_SUCCESS = "PURCHASE_SUCCESS"
export const PURCHASE_FAIL = "PURCHASE_FAIL"
export const PURCHASE_START = "PURCHASE_START"